apiVersion: v1
kind: Service
metadata:
  name: couchdb-peer0-org3
  namespace: org3-local
spec:
  selector:
   app: hyperledger
   role: peer
   org: org3
   name: peer0-org3-ck-com
  externalTrafficPolicy: Local
  externalIPs:
  - %SVC_IP%
  ports:
    - port: 7984
      targetPort: 5984
      name: endpoint
      protocol: TCP
  type: LoadBalancer
  