apiVersion: v1
kind: Service
metadata:
  name: couchdb-peer0-org2
  namespace: org2-local
spec:
  selector:
   app: hyperledger
   role: peer
   org: org2
   name: peer0-org2-ck-com
  externalTrafficPolicy: Local
  externalIPs:
  - %SVC_IP%
  ports:
    - port: 6984
      targetPort: 5984
      name: endpoint
      protocol: TCP
  type: LoadBalancer
  