apiVersion: v1
kind: Service
metadata:
  namespace: org3-local
  name: ca-org3-ck-com
spec:
  selector:
    app: hyperledger
    role: ca
    org: org3
    name: ca-org3-ck-com
  type: LoadBalance
  externalTrafficPolicy: Local
  ports:
    - name: endpoint
      protocol: TCP
      port: 30107
      targetPort: 7054
      nodePort: 30107
