apiVersion: v1
kind: PersistentVolume
metadata:
  name: ica-org1-pv
  labels:
    pv-name: ica-org1-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - nfsvers=4.1
    - rsize=1048576
    - wsize=1048576
    - hard
    - timeo=600
    - retrans=2
  nfs:
    server: %EFSSERVER%
    path: /ica-org1
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace:  org1-local
  name: ica-org1-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  selector:
    matchLabels:
      pv-name: ica-org1-pv
  resources:
    requests:
      storage: 10Mi

