apiVersion: v1
kind: Service
metadata:
  namespace: orderer-local
  name: ca-orderer-ck-com
spec:
  selector:
    app: hyperledger
    role: ca
    org: orderer
    name: ca-orderer-ck-com
  type: LoadBalance
  externalTrafficPolicy: Local
  ports:
    - name: endpoint
      protocol: TCP
      port: 30108
      targetPort: 7054
      nodePort: 30108
