apiVersion: v1
kind: Service
metadata:
  namespace: %ORG%-%HLF_ENV%
  name: ca-%ORG%-ck-com
spec:
  selector:
    app: hyperledger
    role: ca
    org: %ORG%
    name: ca-%ORG%-ck-com
  type: LoadBalance
  externalTrafficPolicy: Local
  ports:
    - name: endpoint
      protocol: TCP
      port: %PORT%
      targetPort: 7054
      nodePort: %PORT%
