apiVersion: v1
kind: Service
metadata:
  namespace:  %ORG%-%HLF_ENV%
  name: ica-%ORG%
spec:
 selector:
   app: hyperledger
   role: ca
   org: %ORG%
   name: ica-%ORG%
 type: NodePort
 ports:
   - name: endpoint
     protocol: TCP
     port: 7054
     targetPort: 7054
     nodePort: %PORT%