apiVersion: v1
kind: Service
metadata:
  namespace: %ORG%-%HLF_ENV%
  name: orderer%NUM%-ck-com
spec:
 selector:
   app: hyperledger
   role: orderer
   org: %ORG%
   name: orderer%NUM%-ck-com
 type: ClusterIP
 ports:
  - name: endpoint
    protocol: TCP
    port: 7050
    targetPort: 7050
    nodePort: %PORT%
  - name: admin
    protocol: TCP
    port: 10000
    targetPort: 10000
    nodePort: %PORT%
  - name: operations
    protocol: TCP
    port: 8443
    targetPort: 8443 