apiVersion: v1
kind: Service
metadata:
  namespace: %ORG%-%HLF_ENV%
  name: peer%NUM%-%ORG%-ck-com
spec:
 selector:
   app: hyperledger
   role: peer
   org: %ORG%
   name: peer%NUM%-%ORG%-ck-com
 type: ClusterIP
 ports:
   - name: endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: %PORT_1%
   - name: endpoint-chaincode
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: %PORT_2%
   - name: endpoint-operations
     protocol: TCP
     port: 9443
     targetPort: 9443