apiVersion: v1
kind: Service
metadata:
  namespace: org2-local
  name: ca-org2-ck-com
spec:
  selector:
    app: hyperledger
    role: ca
    org: org2
    name: ca-org2-ck-com
  type: LoadBalance
  externalTrafficPolicy: Local
  ports:
    - name: endpoint
      protocol: TCP
      port: 30106
      targetPort: 7054
      nodePort: 30106
