apiVersion: v1
kind: Service
metadata:
  namespace: org1-local
  name: peer0-org1-ck-com
spec:
 selector:
   app: hyperledger
   role: peer
   org: org1
   name: peer0-org1-ck-com
 type: ClusterIP
 ports:
   - name: endpoint
     protocol: TCP
     port: 7051
     targetPort: 7051
     nodePort: 30405
   - name: endpoint-chaincode
     protocol: TCP
     port: 7052
     targetPort: 7052
     nodePort: 30406
   - name: endpoint-operations
     protocol: TCP
     port: 9443
     targetPort: 9443