apiVersion: v1
kind: Service
metadata:
  name: couchdb-peer0-org1
  namespace: org1-local
spec:
  selector:
   app: hyperledger
   role: peer
   org: org1
   name: peer0-org1-ck-com
  externalTrafficPolicy: Local
  externalIPs:
  - %SVC_IP%
  ports:
    - port: 5984
      targetPort: 5984
      name: endpoint
      protocol: TCP
  type: LoadBalancer
  